#:schema node_modules/wrangler/config-schema.json
name = "outbound-poc-user-premium"
main = "src/index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

